config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  post 'api/v1/login', to: 'users#login'
  post 'api/v1/register', to: 'users#register'
  get 'api/v1/info', to: 'users#info'
  post 'api/v1/articles', to: 'articles#create'
  patch 'api/v1/articles/:id', to: 'articles#update'
  put 'api/v1/articles/:id', to: 'articles#update'
  get 'api/v1/articles/:id', to: 'articles#show'
  get 'api/v1/articles', to: 'articles#index'
  delete 'api/v1/articles/:id', to: 'articles#destroy'

  match '*path', to: 'pages#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, :body, :user_id, presence: true

  def self.archive_job
    @articles = Article.where("created_at < ?", 0.minutes.ago)
    @articles.update_all(is_archived: true, updated_at: Time.now)
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :user_name, :password_digest, :first_name, :last_name, presence: true
  validates :user_name,
            format: { with: /\A^(.+)@(.+)$\z/, message: 'Invalid email format' },
            uniqueness: { case_sensitive: false },
            length: { minimum: 4, maximum: 254 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  skip_before_action :verify_authenticity_token, if: :json_request?

  def bearer_token
    pattern = /^Bearer /
    header  = request.headers['Authorization']
    header.gsub(pattern, '') if header && header.match(pattern)
  end

  protected

  def json_request?
    request.format.json?
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :resolve_token, only: [:create, :update, :destroy]

  def resolve_token
    begin
      @token_data = JsonWebToken.decode(bearer_token)
    rescue NoMethodError
      nil
    end

    if @token_data.nil?
      head :unauthorized
    else
      @token_data
    end
  end

  def create
    @article = Article.create(title: params[:title], body: params[:body],
                              user_id: @token_data[:id])
    if @article.valid?
      render json: @article
    else
      @payload = { object: @article, errors: @article.errors }
      render json: @payload, status: :method_not_allowed
    end
  end

  def index
    @articles = Article.order(created_at: :desc).joins(:user)
                       .select('articles.*', 'users.user_name',
                               'users.first_name', 'users.last_name')
                       .where(is_archived: false)

    render json: @articles, status: 200
  end

  def show
    @article = Article.joins(:user)
                      .select('articles.*', 'users.user_name',
                              'users.first_name', 'users.last_name')
                      .where(is_archived: false)
                      .find_by_id(params[:id])
    if @article
      render json: @article, status: 200
    else
      head :not_found
    end

  end

  def update
    @article = Article.where(id: params[:id], user_id: @token_data[:id]).first
    @article.update(title: params[:title].nil? ? @article.title : params[:title],
                    body: params[:body].nil? ? @article.body : params[:body],
                    is_private: params[:is_private].nil? ? @article.is_private : params[:is_private],
                    is_archived: params[:is_archived].nil? ? @article.is_archived : params[:is_archived])
    if @article.valid?
      render json: @article, status: 200
    else
      @payload = { object: @article, errors: @article.errors }
      render json: @payload, status: 200
    end
  end

  def destroy
    @article = Article.find_by_id(params[:id])
    if @article
      @article.destroy
      render json: @article, status: 200
    else
      head :not_found
    end

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    @user = User.find_by(user_name: params[:user_name])

    if @user&.authenticate(params[:password])
      token = JsonWebToken.encode(user_name: params[:user_name], id: @user.id)
      render json: { token: token }

    else
      render json: { message: 'unauthorized' }, status: :unauthorized
    end
  end

  # register api request
  def register
    @user = User.create(user_name: params[:user_name],
                        password: params[:password],
                        first_name: params[:first_name],
                        last_name: params[:last_name])

    if @user.valid? && @user.id
      @payload = { user_name: @user.user_name, id: @user.id }
      token = JsonWebToken.encode(@payload)

      render json: { token: token }
    else
      @payload = { user_name: params[:user_name], errors: @user.errors }
      render json: @payload, status: :internal_server_error
    end
  end

  def info
    @user = User.find_by(id: JsonWebToken.decode(bearer_token)[:id])

    if @user
      render json: @user
    else
      render status: :internal_server_error
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Blogging Engine", root_url, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <% if !logged_in? %>
        <li class="nav-item">
          <%= link_to "Register", new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", login_path, class: "nav-link" %>
        </li>
          <% else %>
        <li class="nav-item">
          <%= button_to "Logout", logout_path, :method => "delete" %>
        </li>
          <% end %>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogging Engine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<%= javascript_pack_tag 'index' %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>